language: ruby
rvm:
 - "2.5"
 - "2.6"
 - "2.7"
services:
  - postgresql
  - mysql
before_script:
  - psql -c 'create database travis_ci_test_1;' -U postgres
  - psql -c 'create table knights (name text);' -U postgres
  - psql -c "insert into knights values ('Edric');" -U postgres
  - psql -c 'select * from knights;' -U postgres
  - mysql -e 'create database travis_ci_test_2'
  - mysql travis_ci_test_2 -e 'create table knights (name text);'
  - mysql travis_ci_test_2 -e "insert into knights values ('Arthur');"
  - mysql travis_ci_test_2 -e 'select * from knights;'
script:
 - ruby hello.rb
os: linux
group: stable
dist: rhel
addons:
  yum:
   - docker

